### ISSUE TITLE
Bugged Display Point on cp_steel 2560 x 1440

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#438] opened 2024-01-20 20:10 UTC
Greetings. My control points appear in a weird way during middle of being captured. I use a 2560x1440 resolution and this is cp_steel and I did a fresh reinstall of flawhud and applied my tf2hudeditor settings too

![20240120120643_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/a1f6f523-eafb-459f-8985-1da321964883)
![20240120120832_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/8ea56ba7-035d-4426-81bd-bb2bd37dae2a)

**Comment by CriticalFlaw** [comment] 2024-01-28 14:58
What does it look like on the default HUD?

**Comment by BluestoneDE** [comment] 2024-01-31 19:40
I was able to reproduce this offline on cp_steel and cp_degrootkeep:
1. Go to a CP map where capture prorgess is vertical
2. Start capturing a point
3. Click on Refresh HUD in the Pause Menu while there is capture progress

The problem can be fixed with the same button if there is no capture progress, or just finishing the capture of that point.
This doesn't happen on 5CP and other specific maps because there the point capture progress goes sideways.

**Comment by BluestoneDE** [comment] 2024-01-31 22:34
![grafik](https://github.com/CriticalFlaw/flawhud/assets/65172029/2527537e-d7e4-4cfa-a296-2d553bcbf3f9)
Never mind, it's a problem in default TF2.
It probably says `'class.cfg' not present; not executing` in console for you too.
I managed to get this with a simple `record test` command while capturing and then it says that for me in my console.
### Just verify your game files via Steam and this should go away.

**Comment by CriticalFlaw** [comment] 2024-02-07 00:49
Thank you for double checking.

**Closed as not planned by CriticalFlaw** 2024-02-07 00:49 UTC
Labels: won't fix
