### ISSUE TITLE
Still Medic Spectating problems & Level end result

### ISSUE THREAD

**Issue by h9lk** [CriticalFlaw/flawhud#99] opened 2020-07-24 10:19 UTC
still the patient's nickname, superimposed on the medic's nickname, can't understand % heal and etc

![20200717132504_1](https://user-images.githubusercontent.com/32390006/87782407-16d67300-c83b-11ea-9429-44430c30b538.jpg)

level display is strange, left numbers are smaller, right numbers are larger,
icon blocks level and looks ugly in general

![20200717140634_1](https://user-images.githubusercontent.com/32390006/87782475-37063200-c83b-11ea-9e98-e13d839353e6.jpg)

_Originally posted by @h9lk in https://github.com/CriticalFlaw/FlawHUD/issues/95#issuecomment-660059713_

**Comment by CriticalFlaw** [comment] 2020-07-24 19:10
Just pushed an update moving the spectator TargetID even higher and also fixing the badge and font sizes on the post game match. Please verify.

**Comment by h9lk** [comment] 2020-07-24 21:37
@CriticalFlaw  nothing has changed in end results of game

![20200725002605_1](https://user-images.githubusercontent.com/32390006/88437259-c77ddd00-ce0e-11ea-849c-4a57a5d77bcd.jpg)

heal on medic until now seems good

![20200725003333_1](https://user-images.githubusercontent.com/32390006/88437318-e54b4200-ce0e-11ea-9b82-9e44ba031d63.jpg)

after update - loading in middle began to appear more often

![20200725003232_1](https://user-images.githubusercontent.com/32390006/88437379-07dd5b00-ce0f-11ea-9703-ec1419f2124d.jpg)

**Comment by CriticalFlaw** [comment] 2020-07-24 22:45
The badge is definitely smaller and the current xp label is the same size if you compare with your first image. I'm not sure what controls the rank label, but I'll look into it later because I'm still tier 1 and can't see the extended label.

The loading panel appearing in the middle is not caused by the latest update, it's done rarely by the game when you connect to a different server while already in game.

**Comment by h9lk** [comment] 2020-07-25 07:52
sorry i didn't see, for me it would probably be more convenient

![88437259-c77ddd00-ce0e-11ea-849c-4a57a5d77bcd](https://user-images.githubusercontent.com/32390006/88452183-41d94c00-ce65-11ea-9ec8-42a10604b235.jpg)

**Comment by CriticalFlaw** [comment] 2020-07-26 14:55
Updated to closer match what you had in mind, sorry forgot to take a screenshot

**Comment by h9lk** [comment] 2020-07-26 16:34
> 
> 
> Updated to closer match what you had in mind, sorry forgot to take a screenshot

yey, thx took some screenshots
![20200726190207_1](https://user-images.githubusercontent.com/32390006/88484341-a2a47980-cf76-11ea-9e56-0eaf6376e1df.jpg)

and something new

double countdown?
![20200726190343_1](https://user-images.githubusercontent.com/32390006/88484353-b18b2c00-cf76-11ea-94b2-61925005d896.jpg)

hud cut nickname and score players in minmode
![20200726191246_1](https://user-images.githubusercontent.com/32390006/88484416-0cbd1e80-cf77-11ea-8141-8e225fb8f356.jpg)

think they to close, maybe swap them and move a little away from each other, strange that it's not always shown like this, usual just med nick 

![20200726205636_1](https://user-images.githubusercontent.com/32390006/88486191-ad660b00-cf84-11ea-8758-5da6cadb5027.jpg)

**Comment by CriticalFlaw** [comment] 2020-07-26 18:27
Double countdown is a game bug, the scoreboard was truncated because in higher resolutions the player list goes out of bounds - so because majority of users are on higher resolutions it'll remain as it is. 

The TargetIDs will be left as is as well because this is more of an edge case, and majority of the time when you're in game and being healed while looking at someone else the TargetIDs will be closer.

**Comment by h9lk** [comment] 2020-07-26 18:51
sometime TargetDs be like :o

![20200726213300_1](https://user-images.githubusercontent.com/32390006/88486963-2156e200-cf8a-11ea-966b-8e878b850c80.jpg)

![20200726213550_1](https://user-images.githubusercontent.com/32390006/88486966-23b93c00-cf8a-11ea-9893-e1f8a881ee14.jpg)

**Comment by CriticalFlaw** [comment] 2020-07-26 19:08
It's a delicate balance, moving any of them too much farther away may overlap with some other element we're not currently thinking of :P Anyway, I think the main issues are now fixed so I'm closing the ticket.

**Closed as completed by CriticalFlaw** 2020-07-26 19:08 UTC
Labels: bug report
