### ISSUE TITLE
FPS drops significantly after playing for a while

### ISSUE THREAD

**Issue by derek1906** [CriticalFlaw/flawhud#145] opened 2021-01-31 08:28 UTC
There’s a significant FPS drop (almost halved) when using this hud. The drop seems to only happen after playing for a while, and it doesn’t happen with the default hud. Frame rate would go back to normal if I hold the tab key (which shows the scoreboard and hides the rest of the hud.)

I’m using v2020.1225.

**Comment by CriticalFlaw** [comment] 2021-01-31 18:54
HUDs do not cause frame drops over time and even when they do cause drops it's very minimal and would be noticed instantly. The most likely explanation is that you've either been playing for a long time, played on an unoptimized map or a server with too many players or mods.

**Comment by derek1906** [comment] 2021-01-31 19:19
I don’t think the maps I have been playing on are unoptimized, as I mentioned the frame rate would immediately return to normal (above 100) when I toggle the scoreboard overlay. I’ll test with other custom huds in the meantime and see if I would run into the same issue, which is unfortunate because I like this hud a lot more than the other ones. 

Is there a way to debug in-game where the performance hit is coming from? Thanks in advanced.

**Comment by CriticalFlaw** [comment] 2021-01-31 19:39
I don't think so, but if you can note all instances of when it happens I'm sure there are those within the greater community who would be able to deduce the cause. As it stands, this isn't a widely reported issues so there is not much for me to be done.

**Comment by derek1906** [comment] 2021-02-01 03:06
Thanks for the reply. I did some tests today with a different hud I found on huds.tf (budhud) and I found that the frame rate was consistent the whole time I was playing (>3 hours on the same servers I usually play on), so personally I’m confident that _something_ in this hud is causing the FPS drop. Fortunately from what I see it doesn’t seem like a widespread issue, and in the meantime I’ll just use a different hud until the root cause can be found since the FPS drop is very significant.

**Comment by CriticalFlaw** [comment] 2021-02-01 16:30
Didn't mean to close it. The repo automatically did so when I committed a change. I'm discussing this issue with another HUD developer and I think a potential cause could be the hitmarker animations for a commonly disabled crosshair constantly being called. Extraneous crosshair animations are known to cause FPS drops, so while we continue to look into this - I think this may help mitigate the issue in some way.

Reference: https://www.reddit.com/r/tf2/comments/57760o/cause_and_fix_for_serious_fpsdrop_issue_involving/

**Comment by CriticalFlaw** [comment] 2021-02-01 21:37
Whisker did a benchmark comparing default, budhud and flawhud before and after the change and the results were positive. Where are before it averaged ~158 FPS it went back up to ~232. Could you retest and see if you still experience any significant slowdown?

**Comment by derek1906** [comment] 2021-02-01 21:50
Wow that was quick! I will report back in a few days once I have a chance to test it out, thanks!

**Comment by derek1906** [comment] 2021-02-02 05:26
The commit seems to have resolved the issue! The frame rate was consistent the whole time. Thank you!

**Closed as not planned** 2021-02-02 16:51 UTC
Labels: bug report, won't fix
