### ISSUE TITLE
Shadow misplacement on the match summary screen

### ISSUE THREAD

**Issue by h9lk** [CriticalFlaw/flawhud#111] opened 2020-08-30 20:39 UTC
![20200830233513_1](https://user-images.githubusercontent.com/32390006/91668971-c92b7680-eb19-11ea-9844-7f5d85ed1118.jpg)

![20200831121232_1](https://user-images.githubusercontent.com/32390006/91703765-61aa1100-eb83-11ea-81ba-fefad0d27b0b.jpg)

most often it is not displayed at all, but if displayed on pl this happen

![20200831000401_1](https://user-images.githubusercontent.com/32390006/91669425-8f5c6f00-eb1d-11ea-8e5f-1607f2272760.jpg)

sometimes hightower be like...

![20200831000625_1](https://user-images.githubusercontent.com/32390006/91669480-f5e18d00-eb1d-11ea-8cea-7ae7c1018ae2.jpg)

**Comment by CriticalFlaw** [comment] 2020-09-12 14:23
Fixed the first issue where the winner shadow is misplaced. Regarding the second issue with the duplicate timers. It's being caused by the game not playing the doors animation (the ones where TF2 themed door closes then opens again to start the match), so it won't be fixed.

**Closed as completed by CriticalFlaw** 2020-09-12 14:23 UTC
Labels: bug report
